// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: grow_log.sql

package database

import (
	"context"
	"database/sql"
)

const createLogEntry = `-- name: CreateLogEntry :one
INSERT INTO grow_log(plant_id, plant_type, care_event_id, care_event_name, time_of_care)
SELECT
		p.id,
		p.plant_type,
		e.id,
		e.task_name,
		$3
FROM plants p, events e
WHERE p.id = $1 AND e.id = $2
RETURNING id, plant_id, plant_type, care_event_id, care_event_name, time_of_care, created_at, updated_at
`

type CreateLogEntryParams struct {
	ID         int32
	ID_2       int32
	TimeOfCare sql.NullTime
}

func (q *Queries) CreateLogEntry(ctx context.Context, arg CreateLogEntryParams) (GrowLog, error) {
	row := q.db.QueryRowContext(ctx, createLogEntry, arg.ID, arg.ID_2, arg.TimeOfCare)
	var i GrowLog
	err := row.Scan(
		&i.ID,
		&i.PlantID,
		&i.PlantType,
		&i.CareEventID,
		&i.CareEventName,
		&i.TimeOfCare,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
