// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Event struct {
	ID        int32
	TaskName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GrowLog struct {
	ID            int32
	PlantID       sql.NullInt64
	PlantType     sql.NullString
	CareEventID   sql.NullInt64
	CareEventName sql.NullString
	TimeOfCare    sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Plant struct {
	ID        int32
	PlantType string
	PlantedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}
